# Configuraciones globales de Gradle

# Uso de compilacion en paralelo (mejora velocidad)
org.gradle.parallel=true

# Compilacion bajo demanda (reduce uso de memoria)
org.gradle.configureondemand=true

# Mantiene el daemon activo (evita reinicios de Gradle)
org.gradle.daemon=true

# Ajuste de memoria para el proceso Gradle (ajustado a 1024 MB)
org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8

# Forzar uso de AndroidX
android.useAndroidX=true
